jetmax:
  #list of controllers
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid: { p: 50.0, i: 1.0 }

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: { p: 50.0, i: 1.0 }

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint3
    pid: { p: 50.0, i: 1.0 }

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint4
    pid: { p: 2.0, i: 1.0 }

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint5
    pid: { p: 2.0, i: 1.0 }

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint6
    pid: { p: 1.0, i: 1.0 }

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint7
    pid: { p: 1.0, i: 1.0 }

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint8
    pid: { p: 1.0, i: 1.0 }

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint9
    pid: { p: 1.0, i: 1.0, d: 0.01 }
